<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{2c837950-4eeb-403d-b549-a1fa9ff09b39}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SEQ.iStepN:=30;
Simulation();
POU();
Water_Tank();
POU_1();
POU_3();
SequencyControl();
ValveControl();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="23" Count="0" />
      <LineId Id="28" Count="0" />
      <LineId Id="2" Count="0" />
      <LineId Id="6" Count="0" />
      <LineId Id="10" Count="0" />
      <LineId Id="14" Count="0" />
      <LineId Id="18" Count="1" />
      <LineId Id="27" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>