<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="ValveControl" Id="{3185a286-a2e9-4973-91ab-229e7cba789e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM ValveControl
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="ValveControl">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>